image: alpine/edge
packages:
  - deno
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
  - 6a295705-4fb6-451c-990c-9a12b0aa0dc2
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - setup: |
      echo 'cd openlibrary' >> ~/.buildenv
  - test: |
      deno task check
      deno task test
  - mirror: |
      git push --force --mirror git@github.com:timharek/openlibrary
  - check_release: |
      tag=$(git describe --exact-match --tags HEAD 2>/dev/null || true)
      if [ -z "$tag" ]; then
        echo "Current commit is not a tag: not a new release"
        complete-build
      fi
  - new_release: |
      set +x
      export JSR_API=$(cat ~/jsr_timharek)
      deno publish --allow-slow-types --token $JSR_API
      set -x

